name: Publish to npm

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Execute quando uma tag começando com 'v' for criada

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Set package version from tag (if available)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          npm version $TAG --no-git-tag-version
          echo "Publishing version $TAG"

      - name: Add npmignore file
        run: |
          echo "# Git files" > .npmignore
          echo ".git/" >> .npmignore
          echo ".github/" >> .npmignore
          echo ".gitignore" >> .npmignore
          echo "# Source files" >> .npmignore
          echo "src/" >> .npmignore
          echo "# Config files" >> .npmignore
          echo "tsconfig.json" >> .npmignore
          echo ".eslintrc.js" >> .npmignore
          echo "# Test files" >> .npmignore
          echo "tests/" >> .npmignore
          echo "# Development files" >> .npmignore
          echo "*.log" >> .npmignore
          echo ".env" >> .npmignore
          echo ".env.example" >> .npmignore

      - name: Create .npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: List files to be published
        run: npm pack --dry-run

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
